# Generated by Django 5.1.7 on 2025-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ресторана')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ресторана')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес ресторана')),
                ('phone', models.CharField(max_length=10, verbose_name='Контактный телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Сайт ресторана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('cuisines', models.ManyToManyField(related_name='restourants', to='restaurants.cuisine', verbose_name='Типы кухни')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'ordering': ['-created_at'],
            },
        ),
    ]
