# Generated by Django 5.1.7 on 2025-03-31 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('starter', 'Закуска'), ('main', 'Основное блюдо'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('salad', 'Салат')], max_length=30, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото блюда')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Пункты меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images', verbose_name='Фото ресторана')),
                ('caption', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание блюда')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Фото ресторана',
                'verbose_name_plural': 'Фото ресторанов',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Время открытия')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выходной')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='restaurants.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Часы работы',
                'verbose_name_plural': 'Часы работы',
                'ordering': ['restaurant', 'day_of_week'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
    ]
