# Generated by Django 5.1.7 on 2025-04-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menu_restaurantimage_workinghours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='average_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='establishment_type',
            field=models.CharField(choices=[('bar', 'Бар'), ('restaurant', 'Ресторан')], default='restaurant', max_length=20, verbose_name='Тип заведения'),
        ),
    ]
