# Generated by Django 5.1.7 on 2025-04-04 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('restaurants', '0007_alter_restaurant_options_remove_restaurant_latitude_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Establishment',
        ),
        migrations.RenameModel(
            old_name='RestaurantAdmin',
            new_name='EstablishmentAdmin',
        ),
    ]
