# Generated by Django 5.2.3 on 2025-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ключа')),
                ('key', models.CharField(max_length=54, unique=True, verbose_name='API ключ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
            ],
            options={
                'verbose_name': 'API ключ',
                'verbose_name_plural': 'API ключи ',
            },
        ),
    ]
