# Generated by Django 5.2.3 on 2025-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(verbose_name='Дата и время бронирования')),
                ('duration', models.IntegerField(default=2, verbose_name='Продолжительность (часы)')),
                ('guests_count', models.IntegerField(verbose_name='Количество гостей')),
                ('book_number', models.CharField(default='C2B805BD', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=30)),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Особые пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_datetime'],
            },
        ),
    ]
