# Generated by Django 5.2.3 on 2025-06-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('establishments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='establishments.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='establishments.table', verbose_name='Столик'),
        ),
    ]
