# Generated by Django 5.2.3 on 2025-06-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('establishments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_number',
            field=models.CharField(default='2637A9CE', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='establishments.table', verbose_name='Столик'),
        ),
    ]
