# Generated by Django 5.2.3 on 2025-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_number',
            field=models.CharField(default='F46BADB8', max_length=20, unique=True),
        ),
    ]
