# Generated by Django 5.2.3 on 2025-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_book_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_number',
            field=models.CharField(default='43620257', max_length=20, unique=True),
        ),
    ]
