# Generated by Django 5.2.3 on 2025-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_book_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_number',
            field=models.CharField(default='C872CE64', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер столика'),
        ),
    ]
