# Generated by Django 5.2.3 on 2025-06-29 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='branchimage',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='establishments.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='establishments.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='cuisines',
            field=models.ManyToManyField(related_name='restaurants', to='establishments.cuisine', verbose_name='Типы кухни'),
        ),
        migrations.AddField(
            model_name='branch',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='establishments.establishment', verbose_name='Заведение'),
        ),
        migrations.AddField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='establishments.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='establishments.branch', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='establishments.branch', verbose_name='Ресторан'),
        ),
        migrations.AlterUniqueTogether(
            name='branchadmin',
            unique_together={('user', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('branch', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('branch', 'day_of_week')},
        ),
    ]
