# Generated by Django 5.2.3 on 2025-06-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allow_to_book',
            field=models.BooleanField(default=True, verbose_name='Разрешено бронировать'),
        ),
    ]
