# Generated by Django 5.2.3 on 2025-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления по email'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='promo_notifications',
            field=models.BooleanField(default=False, verbose_name='Рекламные уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, verbose_name='SMS уведомления'),
        ),
    ]
