# Generated by Django 5.2.3 on 2025-07-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0002_initial'),
        ('users', '0002_user_email_notifications_user_last_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='administrated_branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establishments.branch', verbose_name='Филиал'),
        ),
    ]
